use crate::error::AppError;
use crate::models::Article;
use chrono::{DateTime, Utc};
use feed_rs::parser;
use sha2::{Digest, Sha256};
use tracing::{info, warn};

/// Parse RSS/Atom feed from raw bytes and convert to Articles
pub fn parse_rss_feed(raw: &[u8], feed_id: i64) -> Result<Vec<Article>, AppError> {
    // Parse the feed using feed-rs
    let feed = parser::parse(raw)
        .map_err(|e| AppError::FeedParse(format!("Failed to parse RSS feed: {}", e)))?;

    info!(
        "Parsed feed '{}' with {} entries",
        feed.title
            .map(|t| t.content)
            .unwrap_or("Unknown".to_string()),
        feed.entries.len()
    );

    let mut articles = Vec::new();

    for entry in feed.entries {
        // Convert feed entry to Article
        if let Some(article) = convert_entry_to_article(entry, feed_id) {
            articles.push(article);
        }
    }

    Ok(articles)
}

/// Convert a feed_rs Entry to an Article
fn convert_entry_to_article(entry: feed_rs::model::Entry, feed_id: i64) -> Option<Article> {
    // Title is required
    let title_obj = entry.title?;
    let title_text = title_obj.content.trim();
    let title = title_text.to_string();
    if title.is_empty() {
        warn!("Skipping entry with empty title");
        return None;
    }

    // Extract URL (prefer alternate links)
    let url = entry
        .links
        .iter()
        .find(|link| {
            link.rel.as_ref().map(|r| r == "alternate").unwrap_or(false) || link.rel.is_none()
        })
        .or_else(|| entry.links.first())
        .map(|link| link.href.clone());

    // Extract content (prefer summary, then content.body)
    let content = entry
        .summary
        .map(|t| t.content)
        .or_else(|| entry.content.and_then(|c| c.body))
        .filter(|s| !s.trim().is_empty());

    // Extract author
    let author = entry
        .authors
        .first()
        .map(|a| a.name.trim().to_string())
        .filter(|n| !n.is_empty());

    // Parse published date
    let published_at = entry.published.or(entry.updated).and_then(|dt| {
        // Convert chrono::DateTime<FixedOffset> to UTC string
        DateTime::from_timestamp(dt.timestamp(), dt.timestamp_subsec_nanos())
            .map(|dt| dt.with_timezone(&Utc))
            .map(|dt| dt.to_rfc3339())
    });

    // Extract external ID
    let external_id = if !entry.id.is_empty() {
        Some(entry.id.trim().to_string())
    } else {
        url.clone()
    }
    .filter(|id| !id.is_empty());

    // Generate content hash from first 200 characters of content
    let content_hash = content.as_ref().map(|c| {
        // Safe character boundary handling
        let chars: Vec<char> = c.chars().take(200).collect();
        let safe_str: String = chars.into_iter().collect();
        generate_content_hash(&safe_str)
    });

    // Normalize URL
    let url_normalized = url.as_ref().map(|u| normalize_url(u));

    // Create article
    Some(Article {
        id: 0, // Will be set by database
        feed_id,
        external_id,
        title: title.clone(),
        url,
        url_normalized,
        content: content.clone(),
        summary: None, // Will be generated by AI in Phase 2
        author,
        published_at,
        importance_score: 0.0, // Will be calculated in Phase 2
        is_read: false,
        is_bookmarked: false,
        is_duplicate: false,
        duplicate_of: None,
        language: detect_language(&title, content.as_deref()),
        thumbnail_url: None, // Could extract from media:thumbnail in future
        content_hash,
        metadata: None, // Could store additional metadata in future
        created_at: Utc::now().to_rfc3339(),
    })
}

/// Generate SHA-256 hash of content
pub fn generate_content_hash(content: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(content.as_bytes());
    format!("{:x}", hasher.finalize())
}

/// Normalize URL for deduplication
fn normalize_url(url: &str) -> String {
    let mut normalized = url.trim().to_string();

    // Remove fragment
    if let Some(hash_pos) = normalized.rfind('#') {
        normalized.truncate(hash_pos);
    }

    // Remove trailing slash
    normalized = normalized.trim_end_matches('/').to_string();

    // Convert to lowercase
    normalized = normalized.to_lowercase();

    normalized
}

/// Simple language detection (very basic, could be improved)
fn detect_language(title: &str, content: Option<&str>) -> Option<String> {
    let text = format!("{} {}", title, content.unwrap_or(""));

    // Simple heuristic: if contains Japanese characters, assume Japanese
    if text.chars().any(|c| {
        (0x3040..=0x309F).contains(&(c as u32)) || // Hiragana
        (0x30A0..=0x30FF).contains(&(c as u32)) || // Katakana
        (0x4E00..=0x9FFF).contains(&(c as u32)) // Kanji
    }) {
        Some("ja".to_string())
    } else {
        Some("en".to_string()) // Default to English
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    #[test]
    fn test_generate_content_hash() {
        let hash1 = generate_content_hash("test content");
        let hash2 = generate_content_hash("test content");
        let hash3 = generate_content_hash("different content");

        assert_eq!(hash1, hash2);
        assert_ne!(hash1, hash3);

        // Hash should be 64 characters (SHA-256 hex)
        assert_eq!(hash1.len(), 64);
    }

    #[test]
    fn test_normalize_url() {
        assert_eq!(
            normalize_url("https://example.com/path#fragment"),
            "https://example.com/path"
        );
        assert_eq!(
            normalize_url("https://example.com/path/"),
            "https://example.com/path"
        );
        assert_eq!(
            normalize_url("HTTPS://EXAMPLE.COM/PATH"),
            "https://example.com/path"
        );
        assert_eq!(
            normalize_url("https://example.com/path/?query=1#frag"),
            "https://example.com/path/?query=1"
        );
    }

    #[test]
    fn test_detect_language() {
        assert_eq!(detect_language("テスト", None), Some("ja".to_string()));
        assert_eq!(detect_language("test", None), Some("en".to_string()));
        assert_eq!(detect_language("テストtest", None), Some("ja".to_string()));
        assert_eq!(
            detect_language("テスト", Some("content")),
            Some("ja".to_string())
        );
    }

    #[test]
    fn test_convert_entry_without_title() {
        let entry = feed_rs::model::Entry::default();

        let article = convert_entry_to_article(entry, 1);

        assert!(article.is_none());
    }

    #[test]
    fn test_parse_rss_feed() {
        let rss_content = r##"<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>Test Feed</title>
<item>
<title>Test Article</title>
<link>https://example.com/article</link>
<description>Test description</description>
<pubDate>Wed, 18 Jun 2024 12:00:00 GMT</pubDate>
</item>
</channel>
</rss>"##;

        let result = parse_rss_feed(rss_content.as_bytes(), 1);

        assert!(result.is_ok());
        let articles = result.unwrap();
        assert_eq!(articles.len(), 1);
        assert_eq!(articles[0].title, "Test Article");
        assert_eq!(
            articles[0].url,
            Some("https://example.com/article".to_string())
        );
    }

    #[test]
    fn test_parse_atom_feed() {
        let atom_content = r##"<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
<title>Test Feed</title>
<entry>
<title>Test Article</title>
<link href="https://example.com/article" />
<summary>Test description</summary>
<updated>2024-06-18T12:00:00Z</updated>
</entry>
</feed>"##;

        let result = parse_rss_feed(atom_content.as_bytes(), 1);

        assert!(result.is_ok());
        let articles = result.unwrap();
        assert_eq!(articles.len(), 1);
        assert_eq!(articles[0].title, "Test Article");
        assert_eq!(
            articles[0].url,
            Some("https://example.com/article".to_string())
        );
    }
}
